CALL MP_MPB.DROP_TABLE_IF_EXISTS('MP_MPB','ACC_MOV_HISTORY_REPORT',MSG);
CREATE MULTISET TABLE MP_MPB.ACC_MOV_HISTORY_REPORT AS (
SELECT 
			TOP 1 *
FROM MP_MPB.USER_MOV_HISTORY
WHERE CUS_CUST_ID = 32974675
) WITH DATA PRIMARY INDEX (CUS_CUST_ID, CUS_CUST_ID_BUY, CUS_CUST_ID_SEL);
DELETE FROM MP_MPB.ACC_MOV_HISTORY_REPORT WHERE CUS_CUST_ID = 32974675;

