CALL MP_MPB.DROP_TABLE_IF_EXISTS('MP_MPB','CBK_IZA',MSG);

CREATE MULTISET TABLE MP_MPB.CBK_IZA (
PAYMENT VARCHAR(255),
NRNSU VARCHAR(255),
NRAUTORIZACAO VARCHAR(255),
DATA_VENDA VARCHAR(255),
VALOR_VENDA VARCHAR(255),
DSMOTIVOAJUSTE VARCHAR(255),
DATA_AJUSTE VARCHAR(255),
VALOR_AJUSTE VARCHAR(255),
TOTAL VARCHAR(255)
) PRIMARY INDEX (PAYMENT);


