CALL MP_MPB.DROP_TABLE_IF_EXISTS('MP_MPB','DOC_INPUT',MSG);

CREATE MULTISET TABLE MP_MPB.DOC_INPUT (
COMPUTADOR_DESTINO  VARCHAR(255),
NUMERO_CASO VARCHAR(255),
EMAIL_CASO VARCHAR(255),
DATA_OFICIO VARCHAR(255),
NUMERO_PROCESSO VARCHAR(255),
NOME_TRIBUNAL VARCHAR(255),
NOME_MAGISTRADO VARCHAR(255),
CARGO_MAGISTRADO VARCHAR(255),
RANGE_MIN VARCHAR(255),
RANGE_MAX VARCHAR(255),
DOC_NUMBER VARCHAR(255),
CREATED_AT VARCHAR(255)
) PRIMARY INDEX (DOC_NUMBER);
