CALL MP_MPB.DROP_TABLE_IF_EXISTS('MP_MPB','OFICIOS_DB',MSG);
CREATE MULTISET TABLE MP_MPB.OFICIOS_DB AS (
SELECT TOP 1
			UMI.CUS_CUST_ID,
			UMI.MOV_MOVE_ID,
			UMI.MOV_CREATED_DT,
            CAST(NULL AS VARCHAR(255)) AS MOV_CREATED_DT_CALC,
			UMI.MOV_DETAIL,
            UMI.OFICIO_NUMBER,
            UMI.OFICIO_CREATED_AT,
			UMI.MOV_TYPE_ID,	
			UMI.PAY_OPERATION_TYPE_ID,
			UMI.MOV_FINANCIAL_ENTITY_ID,	
			UMI.WIT_WITHDRAW_ID,
			UMI.MOV_AMOUNT,
            CAST(NULL AS VARCHAR(255)) AS MOV_AMOUNT_CALC,
			UMI.ACCOUNT_TYPE,
			UMI.WIT_BANK_ACC_NUMBER,
            UMI.WITHDRAWAL_STATUS,
			UMI.RECEIVING_ACCOUNT_HOLDER_NAME,
			UMI.RECEIVING_ACCOUNT_HOLDER_DOC_NUMBER,
			UMI.BANK_ID,
			UMI.WIT_BANK_ACC_BRANCH_ID,
			UMI.RECEIVING_BANK_NAME,
			UMI.PAYER_BANK_NAME,
			UMI.WITHDRAWAL_METHOD,
			UMI.WITHDRAWAL_AMOUNT,
			CI.CUS_CUST_ID_BUY,
			CI.CUS_FULL_NAME_BUY,
			CI.CUS_CUST_DOC_NUMBER_BUY,
			CI.CUS_CUST_DOC_TYPE_BUY,
			CI.CUS_ADDRESS_BUY,
			CAST(NULL AS VARCHAR(255)) AS CUS_RU_SINCE_DT_BUY,
			CI.CUS_RU_SINCE_DT_MP_BUY,
			CI.CUS_CUST_STATUS_MP_BUY,
			CI.CUS_PHONE_BUY,
			CI.CUS_COUNTRY_BUY,
			CI.CUS_STATE_BUY,
            CAST(NULL AS VARCHAR(255)) AS UF,
			CI.CUS_CITY_BUY,
			CI.CUS_ZIP_CODE_BUY,
			CI.CUS_CUST_ID_SEL,
			CI.CUS_FULL_NAME_SEL,
			CI.CUS_CUST_DOC_NUMBER_SEL,
			CI.CUS_CUST_DOC_TYPE_SEL,
			CI.CUS_ADDRESS_SEL,
			CI.CUS_RU_SINCE_DT_SEL,
			CI.CUS_RU_SINCE_DT_MP_SEL,
			CI.CUS_CUST_STATUS_MP_SEL,
			CI.CUS_PHONE_SEL,
			CI.CUS_COUNTRY_SEL,
			CI.CUS_STATE_SEL,
			CI.CUS_CITY_SEL,
			CI.CUS_ZIP_CODE_SEL,
			CURRENT_DATE AS GENERATED_AT,
			'002' AS HAD_REPORT
FROM MP_MPB.ACC_MOV_HISTORY_REPORT UMI
LEFT JOIN MP_MPB.CUS_INFO CI ON CI.MOV_MOVE_ID = UMI.MOV_MOVE_ID
WHERE 1=1
			AND UMI.MOV_DETAIL IN ('cellphone_recharge', 'money_transfer', 'payment', 'account_fund', 'withdraw') -- queremos apenas as movimentacoes de saque e movimentacao de in/out
			AND UMI.MOV_TYPE_ID IN ('expense', 'fund', 'income') -- expense = withdraw, fund = envio e income = recebimento
			AND UMI.PAY_OPERATION_TYPE_ID IS NOT NULL
) WITH DATA PRIMARY INDEX (OFICIO_NUMBER);
DELETE FROM MP_MPB.OFICIOS_DB WHERE MOV_CREATED_DT IS NOT NULL;



