CALL MP_MPB.DROP_TABLE_IF_EXISTS('MP_MPB','DOC_INPUT_MATCH',MSG);
CREATE MULTISET TABLE MP_MPB.DOC_INPUT_MATCH AS (
SELECT * FROM (
SELECT 
      DI.*,
      C.CUS_CUST_ID
FROM MP_MPB.DOC_INPUT DI
LEFT JOIN WHOWNER.LK_CUS_CUSTOMERS_DATA C ON C.CUS_CUST_DOC_NUMBER = DI.DOC_NUMBER AND C.SIT_SITE_ID_CUS = 'MLB'
) BASE WHERE BASE.CUS_CUST_ID IS NOT NULL
) WITH DATA PRIMARY INDEX (CUS_CUST_ID);