INSERT INTO MP_MPB.OFICIOS_DB 
SELECT
			UMI.CUS_CUST_ID,
			UMI.MOV_MOVE_ID,
			UMI.MOV_CREATED_DT,	
      TO_CHAR(UMI.MOV_CREATED_DT, 'DDMMYYYY') AS MOV_CREATED_DT_CALC,
			UMI.MOV_DETAIL,
      OREPLACE(OREPLACE(UMI.OFICIO_NUMBER, '/', ''), '\', '') AS OFICIO_NUMBER,
      UMI.OFICIO_CREATED_AT,
			UMI.MOV_TYPE_ID,	
			UMI.PAY_OPERATION_TYPE_ID,
			UMI.MOV_FINANCIAL_ENTITY_ID,	
			UMI.WIT_WITHDRAW_ID,
			UMI.MOV_AMOUNT,
			OREPLACE(CAST((CASE WHEN UMI.MOV_AMOUNT <= 0.00 THEN UMI.MOV_AMOUNT *-1 ELSE UMI.MOV_AMOUNT END) AS VARCHAR(255)), '.', '') AS MOV_AMOUNT_CALC,
			UMI.ACCOUNT_TYPE,
      OREPLACE(OREPLACE(UMI.WIT_BANK_ACC_NUMBER, '/', ''), '-', '') AS WIT_BANK_ACC_NUMBER,
      UMI.WITHDRAWAL_STATUS,
			UMI.RECEIVING_ACCOUNT_HOLDER_NAME,
			UMI.RECEIVING_ACCOUNT_HOLDER_DOC_NUMBER,
			UMI.BANK_ID,
			UMI.WIT_BANK_ACC_BRANCH_ID,
			UMI.RECEIVING_BANK_NAME,
			UMI.PAYER_BANK_NAME,
			UMI.WITHDRAWAL_METHOD,
			UMI.WITHDRAWAL_AMOUNT,
			CI.CUS_CUST_ID_BUY,
			CI.CUS_FULL_NAME_BUY,
			CI.CUS_CUST_DOC_NUMBER_BUY,
			CI.CUS_CUST_DOC_TYPE_BUY,
			CI.CUS_ADDRESS_BUY,
      TO_CHAR(CI.CUS_RU_SINCE_DT_BUY, 'DDMMYYYY') AS CUS_RU_SINCE_DT_BUY,
			CI.CUS_RU_SINCE_DT_MP_BUY,
			CI.CUS_CUST_STATUS_MP_BUY,
			CI.CUS_PHONE_BUY,
			CI.CUS_COUNTRY_BUY,
			CI.CUS_STATE_BUY,
			CASE WHEN CI.CUS_STATE_BUY = 'RONDÔNIA' THEN 'RO'
						WHEN CI.CUS_STATE_BUY = 'ACRE' THEN 'AC'
						WHEN CI.CUS_STATE_BUY = 'AMAZONAS' THEN 'AM'
						WHEN CI.CUS_STATE_BUY = 'RORAIMA' THEN 'RR'
						WHEN CI.CUS_STATE_BUY = 'PARÁ' THEN 'PA'
						WHEN CI.CUS_STATE_BUY = 'AMAPÁ' THEN 'AP'
						WHEN CI.CUS_STATE_BUY = 'TOCANTINS' THEN 'TO'
						WHEN CI.CUS_STATE_BUY = 'MARANHÃO' THEN 'MA'
						WHEN CI.CUS_STATE_BUY = 'PIAUÍ' THEN 'PI'
						WHEN CI.CUS_STATE_BUY = 'CEARÁ' THEN 'CE'
						WHEN CI.CUS_STATE_BUY = 'RIO GRANDE DO NORTE' THEN 'RN'
						WHEN CI.CUS_STATE_BUY = 'PARAÍBA' THEN 'PB'
						WHEN CI.CUS_STATE_BUY = 'PERNAMBUCO' THEN 'PE'
						WHEN CI.CUS_STATE_BUY = 'ALAGOAS' THEN 'AL'
						WHEN CI.CUS_STATE_BUY = 'SERGIPE' THEN 'SE'
						WHEN CI.CUS_STATE_BUY = 'BAHIA' THEN 'BA'
						WHEN CI.CUS_STATE_BUY = 'MINAS GERAIS' THEN 'MG'
						WHEN CI.CUS_STATE_BUY = 'ESPÍRITO SANTO' THEN 'ES'
						WHEN CI.CUS_STATE_BUY = 'RIO DE JANEIRO' THEN 'RJ'
						WHEN CI.CUS_STATE_BUY = 'SÃO PAULO' THEN 'SP'
						WHEN CI.CUS_STATE_BUY = 'PARANÁ' THEN 'PR'
						WHEN CI.CUS_STATE_BUY = 'SANTA CATARINA' THEN 'SC'
						WHEN CI.CUS_STATE_BUY = 'RIO GRANDE DO SUL' THEN 'RS'
						WHEN CI.CUS_STATE_BUY = 'MATO GROSSO DO SUL' THEN 'MS'
						WHEN CI.CUS_STATE_BUY = 'MATO GROSSO' THEN 'MT'
						WHEN CI.CUS_STATE_BUY = 'GOIÁS' THEN 'GO'
						WHEN CI.CUS_STATE_BUY = 'DISTRITO FEDERAL' THEN 'DF'
			 			ELSE NULL
			 	END AS UF,
			CI.CUS_CITY_BUY,
			CI.CUS_ZIP_CODE_BUY,
			CI.CUS_CUST_ID_SEL,
			CI.CUS_FULL_NAME_SEL,
			CI.CUS_CUST_DOC_NUMBER_SEL,
			CI.CUS_CUST_DOC_TYPE_SEL,
			CI.CUS_ADDRESS_SEL,
			CI.CUS_RU_SINCE_DT_SEL,
			CI.CUS_RU_SINCE_DT_MP_SEL,
			CI.CUS_CUST_STATUS_MP_SEL,
			CI.CUS_PHONE_SEL,
			CI.CUS_COUNTRY_SEL,
			CI.CUS_STATE_SEL,
			CI.CUS_CITY_SEL,
			CI.CUS_ZIP_CODE_SEL,
			CURRENT_DATE AS GENERATED_AT,
			'002' AS HAD_REPORT
FROM MP_MPB.ACC_MOV_HISTORY_REPORT UMI
LEFT JOIN MP_MPB.CUS_INFO CI ON CI.MOV_MOVE_ID = UMI.MOV_MOVE_ID
WHERE 1=1
			AND UMI.MOV_DETAIL IN ('cellphone_recharge', 'money_transfer', 'payment', 'account_fund', 'withdraw') -- queremos apenas as movimentacoes de saque e movimentacao de in/out
			AND UMI.MOV_TYPE_ID IN ('expense', 'fund', 'income') -- expense = withdraw, fund = envio e income = recebimento
			AND UMI.PAY_OPERATION_TYPE_ID IS NOT NULL;
			

INSERT INTO MP_MPB.OFICIOS_DB 
SELECT
			NULL AS CUS_CUST_ID,
			NULL AS MOV_MOVE_ID,
			NULL AS MOV_CREATED_DT,
            NULL AS MOV_CREATED_DT_CALC,
			NULL AS MOV_DETAIL,
			DI.COMPUTADOR_DESTINO||'-'||DI.NUMERO_CASO AS OFICIO_NUMBER,
            DI.CREATED_AT AS OFICIO_CREATED_AT,
			NULL AS MOV_TYPE_ID,
			NULL AS PAY_OPERATION_TYPE_ID,
			NULL AS MOV_FINANCIAL_ENTITY_ID,
			NULL AS WIT_WITHDRAW_ID,
			NULL AS MOV_AMOUNT,
			NULL AS MOV_AMOUNT_CALC,
			NULL AS ACCOUNT_TYPE,
			NULL AS WIT_BANK_ACC_NUMBER,
			NULL AS WITHDRAWAL_STATUS,
			NULL AS RECEIVING_ACCOUNT_HOLDER_NAME,
			NULL AS RECEIVING_ACCOUNT_HOLDER_DOC_NUMBER,
			NULL AS BANK_ID,
			NULL AS WIT_BANK_ACC_BRANCH_ID,
			NULL AS RECEIVING_BANK_NAME,
			NULL AS PAYER_BANK_NAME,
			NULL AS WITHDRAWAL_METHOD,
			NULL AS WITHDRAWAL_AMOUNT,
			NULL AS CUS_CUST_ID_BUY,
			NULL AS CUS_FULL_NAME_BUY,
			DI.DOC_NUMBER AS CUS_CUST_DOC_NUMBER_BUY,
			NULL AS CUS_CUST_DOC_TYPE_BUY,
			NULL AS CUS_ADDRESS_BUY,
			NULL AS CUS_RU_SINCE_DT_BUY,
			NULL AS CUS_RU_SINCE_DT_MP_BUY,
			NULL AS CUS_CUST_STATUS_MP_BUY,
			NULL AS CUS_PHONE_BUY,
			NULL AS CUS_COUNTRY_BUY,
			NULL AS CUS_STATE_BUY,
			NULL AS UF,
			NULL AS CUS_CITY_BUY,
			NULL AS CUS_ZIP_CODE_BUY,
			NULL AS CUS_CUST_ID_SEL,
			NULL AS CUS_FULL_NAME_SEL,
			NULL AS CUS_CUST_DOC_NUMBER_SEL,
			NULL AS CUS_CUST_DOC_TYPE_SEL,
			NULL AS CUS_ADDRESS_SEL,
			NULL AS CUS_RU_SINCE_DT_SEL,
			NULL AS CUS_RU_SINCE_DT_MP_SEL,
			NULL AS CUS_CUST_STATUS_MP_SEL,
			NULL AS CUS_PHONE_SEL,
			NULL AS CUS_COUNTRY_SEL,
			NULL AS CUS_STATE_SEL,
			NULL AS CUS_CITY_SEL,
			NULL AS CUS_ZIP_CODE_SEL,
			CURRENT_DATE AS GENERATED_AT,
			'001' AS HAD_REPORT
FROM MP_MPB.DOC_INPUT DI 
LEFT JOIN MP_MPB.DOC_INPUT_MATCH DIM ON DIM.DOC_NUMBER = DI.DOC_NUMBER
WHERE DIM.CUS_CUST_ID IS NULL AND DI.CREATED_AT = (SELECT MAX(CREATED_AT) FROM MP_MPB.DOC_INPUT);