INSERT INTO MP_MPB.DOC_INPUT_MATCH
SELECT * FROM (
SELECT 
      DI.*,
      C.CUS_CUST_ID
FROM MP_MPB.DOC_INPUT DI
LEFT JOIN WHOWNER.LK_CUS_CUSTOMERS_DATA C ON C.CUS_CUST_DOC_NUMBER = DI.DOC_NUMBER AND C.SIT_SITE_ID_CUS = 'MLB'
) BASE WHERE BASE.CUS_CUST_ID IS NOT NULL AND BASE.CREATED_AT = (SELECT MAX(CREATED_AT) FROM MP_MPB.DOC_INPUT);