CALL MP_MPB.DROP_TABLE_IF_EXISTS('MP_MPB','USER_MOV_HISTORY',MSG);
CREATE MULTISET TABLE MP_MPB.USER_MOV_HISTORY AS (
SELECT
			M.CUS_CUST_ID,
			M.CUS_CUST_ID_SEL,
			M.CUS_CUST_ID_BUY,
			M.MOV_MOVE_ID,
			M.MOV_CREATED_DT,	
			M.MOV_DETAIL,
			M.MOV_TYPE_ID,	
            M.PAY_PAYMENT_ID,
            M.PAY_REASON_ID,
			M.PAY_OPERATION_TYPE_ID,
			M.MOV_FINANCIAL_ENTITY_ID,	
			M.WIT_WITHDRAW_ID,
			M.MOV_AMOUNT,
			W.ACCOUNT_TYPE,
			W.WIT_BANK_ACC_NUMBER,
            W.WITHDRAWAL_STATUS,
			W.RECEIVING_ACCOUNT_HOLDER_NAME,
			W.RECEIVING_ACCOUNT_HOLDER_DOC_NUMBER,
			W.BANK_ID,
			W.WIT_BANK_ACC_BRANCH_ID,
			W.RECEIVING_BANK_NAME,
			W.PAYER_BANK_NAME,
			W.WITHDRAWAL_METHOD,
			W.WITHDRAWAL_AMOUNT,
            M.OFICIO_NUMBER,
            M.OFICIO_CREATED_AT
FROM MP_MPB.ACC_MOV_HISTORY M
LEFT JOIN MP_MPB.ACC_WITHDRAWAL_HISTORY W ON W.WIT_WITHDRAWAL_ID = M.WIT_WITHDRAW_ID
) WITH DATA PRIMARY INDEX (CUS_CUST_ID);