SELECT
			DISTINCT
			COMPUTADOR_DESTINO||'-'||NUMERO_CASO AS OFICIO_NUMBER,
			EMAIL_CASO,
			DATA_OFICIO,
			NUMERO_PROCESSO,
			NOME_TRIBUNAL,
			NOME_MAGISTRADO,
			CARGO_MAGISTRADO
FROM MP_MPB.DOC_INPUT WHERE COMPUTADOR_DESTINO||'-'||NUMERO_CASO IN ('018-PCSP-000566-99')AND CREATED_AT = '2020-03-25' ;

