CALL MP_MPB.DROP_TABLE_IF_EXISTS('MP_MPB','ACC_WITHDRAWAL_HISTORY',MSG);
CREATE MULTISET TABLE MP_MPB.ACC_WITHDRAWAL_HISTORY AS (
SELECT
			WIT.CUS_CUST_ID,
			WIT_WITHDRAWAL_ID,
			WIT_BANK_ACC_TYPE_ID AS ACCOUNT_TYPE,
			WIT_BANK_ACC_NUMBER,
			CASE
					WHEN WIT_STATUS_ID IN ('APPROVED') THEN WIT_STATUS_ID
					ELSE WIT_STATUS_ID || '_'|| WIT_STATUS_DETAIL_ID
			END AS WITHDRAWAL_STATUS,
			WIT.WIT_BANK_ACC_HOLDER_ID AS RECEIVING_ACCOUNT_HOLDER_NAME,
			WIT.WIT_BANK_ACC_ID_NUMBER AS RECEIVING_ACCOUNT_HOLDER_DOC_NUMBER,
			WIT.WIT_BANK_ACC_BANK_ID AS BANK_ID,
			WIT_BANK_ACC_BRANCH_ID,
			OREPLACE(REGEXP_REPLACE(WIT_BANK_ACC_BANK_DESC, '[0-9]+','',1,0, 'i'),' - ', '') AS RECEIVING_BANK_NAME,
			CASE WIT_PAYER_BANK_ID
					WHEN 'BRADESCO_WITHDRAW' THEN 'BANCO BRADESCO'
					WHEN 'BBVA' THEN 'BANCO BVA'
					WHEN 'CAIXA_ECONOMICA' THEN 'BANCO CAIXA ECONOMICA FEDERAL'
					WHEN 'CITIBANK_CB' THEN 'BANCO CITIBANK'
					WHEN 'SANTANDER' THEN 'BANCO SANTANDER'
					WHEN 'BRASIL' THEN 'BANCO DO BRASIL'
					WHEN 'CITIBANK' THEN 'BANCO CITIBANK'
					WHEN 'ITAU' THEN 'BANCO ITAU'
					ELSE WIT_PAYER_BANK_ID
			END AS PAYER_BANK_NAME,
			WIT.WIT_METHOD_ID AS WITHDRAWAL_METHOD,
			WIT_WITHDRAWAL_AMT AS WITHDRAWAL_AMOUNT,
			WIT_CREATED_DATETIME,
			WIT_CONFIRMED_DATETIME AS CONFIRMATION_DATE,
            CAST(NULL AS VARCHAR(255)) AS OFICIO_NUMBER,
            CAST(NULL AS VARCHAR(255)) AS OFICIO_CREATED_AT
FROM WHOWNER.BT_MP_WITHDRAWALS WIT
		INNER JOIN LK_MP_WITHDRAWAL_BANKS BA ON BA.WIT_BANK_ACC_BANK_ID = WIT.WIT_BANK_ACC_BANK_ID AND BA.SIT_SITE_ID IN ('MLB')
WHERE 1=1
			AND WIT.SIT_SITE_ID IN ('MLB')
			AND WITHDRAWAL_STATUS = 'approved'
			AND WIT_CREATED_DT BETWEEN  (SELECT MIN(RANGE_MIN) AS RANGE_MIN FROM MP_MPB.DOC_INPUT_MATCH WHERE CREATED_AT = (SELECT MAX(CREATED_AT) FROM MP_MPB.DOC_INPUT)) AND (SELECT MAX(RANGE_MAX) AS RANGE_MIN FROM MP_MPB.DOC_INPUT_MATCH WHERE CREATED_AT = (SELECT MAX(CREATED_AT) FROM MP_MPB.DOC_INPUT))
			AND WIT.WIT_BANK_ACC_BANK_ID IS NOT NULL
			AND WIT.CUS_CUST_ID IN (SELECT CUS_CUST_ID FROM MP_MPB.DOC_INPUT_MATCH WHERE CREATED_AT = (SELECT MAX(CREATED_AT) FROM MP_MPB.DOC_INPUT))
) WITH DATA PRIMARY INDEX (CUS_CUST_ID, RECEIVING_ACCOUNT_HOLDER_DOC_NUMBER);
